### ISSUE TITLE
New config schema

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly#42]
The current config schema could not satisfy our needs any more.
E.g. Testbed config has controller info and params mixed together, which makes it hard to figure out what resources can be shared in a test bed.

We need to redefine the config so it can carry our feature roadmap.

Some preliminary requirements:
1. Separate controller config and test params should be separate in testbed config.
2. Able to differentiate inherent property of a controller (a phone has bt chip), and property that is assigned (a phone is the caller)
3. Easy to mark whether a controller is sharable, and how sharable it is (can be used in X tests in parallel)
4. Maybe a new format to make it more readable and easier to construct complex configuration.
5. Consider exposing more information of the MH invocation to test cases.

**Comment by dthkao** [comment]
Related: test-side assertions on whether the testbed supports the test is limited (only a count that the number of devices is correct). We should provide a method for the test to define a testbed "interface".

**Comment by xpconanfan** [comment]
Update: design in progress

**Comment by xpconanfan** [comment]
Design complete, implementation in progress.

Here's an example showing the old format vs new format:

A sample config in old Json-based format.
```json
{
    "testbed": [{
        "_description": "A testbed with two Android devices.",
        "name": "SampleTestBedA",
        "AndroidDevice": [{
            "serial": "xyz123",
            "skip_sl4a": true,
            "label": "caller"
        }, {
            "serial": "xyz456",
            "label": "callee"
        }],
        "laughter": "hahahe",
        "cry": "wmmmm",
        "icecream_type": "strawberry"
    },
    {
        "_description": "A testbed that picks up all connected Android devices.",
        "name": "SampleTestBedB",
        "AndroidDevice": "*",
        "laughter": "hahahe",
        "cry": "wmmmm"
    }],
    "logpath": "/tmp/logs",
    "icecream_type": "vanilla"
}
```

The equivalent config in new YAML-based format.
```yaml
---
GlobalParams: &GlobalParams
  icecream_type: vanilla

TestBeds:
  - Name: SampleTestBedA
    # A testbed with two Android devices.
    Controllers:
      AndroidDevice:
        - serial: xyz123
          skip_sl4a: True
          label: caller
        - serial: xyz456
          label: callee
    TestParams:
      <<: *GlobalParams
      laughter: hahahe
      cry: wmmmm
      icecream_type: strawberry
  - Name: SampleTestBedB
    # A testbed that picks up all connected Android devices.
    Controllers:
      AndroidDevice: "*"
    TestParams:
      <<: *GlobalParams
      laughter: hahahe
      cry: wmmmm
...
```
